export const colors = {
	black: '#000000',
	white: '#ffffff',
	blueLighter: '#dcf6fe',
	blueLight: '#b9ecfd',
	blue: '#4db7ef',
	blueDark: '#266dab',
	blueDarker: '#0e3671',
	greenLighter: '#d5fbe4',
	greenLight: '#b1f6cd',
	green: '#058b7b',
	greenDark: '#41907a',
	greenDarker: '#275c5d',
	greyLighter: '#f6fbfe',
	greyLight: '#e2edf4',
	grey: '#becfda',
	greyDark: '#445964',
	greyDarker: '#2f3d46',
	yellowLighter: '#fffacc',
	yellowLight: '#fff399',
	yellow: '#ffda05',
	yellowDark: '#b68302',
	yellowDarker: '#935901',
	redLighter: '#f8d3d3',
	redLight: '#f0adb8',
	red: '#ce3b4c',
	redDark: '#b0304c',
	redDarker: '#932548',
};

export const themeColors = {
	primary: colors.green,
	primaryLight: colors.greenLight,
	primaryDark: colors.greenDark,
	secondary: colors.greyDark,
	secondaryLight: colors.greyLight,
	secondaryDark: colors.greyDarker,
	success: colors.green,
	successLight: colors.greenLight,
	successDark: colors.greenDark,
	danger: colors.red,
	dangerLight: colors.redLight,
	dangerDark: colors.redDark,
	warning: colors.yellow,
	warningLight: colors.yellowLight,
	warningDark: colors.yellowDark,
	info: colors.blue,
	infoLight: colors.blueLight,
	infoDark: colors.blueDark,
	disabled: colors.grey,
	textDisabled: colors.grey,
	backgroundDisabled: colors.greyLight,
};
